"""
DO NOT EDIT - Auto-generated file
Generated by talon-pack v3.0.0

Detects if this package is loaded from multiple locations.
"""
from talon import actions

_duplicate = False
try:
    actions.user.input_map_version()
    _duplicate = True
except Exception:
    pass

if _duplicate:
    print("============================================================")
    print("DUPLICATE PACKAGE: talon-input-map (user.input_map)")
    print("")
    print("  talon-input-map is already loaded from another location.")
    print("  If using talon-gamekit, remove your standalone talon-input-map clone.")
    print("  Only one copy of talon-input-map can exist in talon/user.")
    print("============================================================")
    raise RuntimeError(
        "Duplicate package: talon-input-map (user.input_map) is already loaded."
    )
