"""
DO NOT EDIT - Auto-generated file
Generated by talon-manifest-tools v2.1.0

This file provides:
- Package version checking via input_map_version() action
"""
import json
import os
from talon import Module

mod = Module()

@mod.action_class
class Actions:
    def input_map_version() -> tuple[int, int, int]:
        """Returns the package version as (major, minor, patch)"""
        manifest_path = os.path.join(os.path.dirname(__file__), 'manifest.json')
        with open(manifest_path, 'r', encoding='utf-8') as f:
            version_str = json.load(f)['version']
        return tuple(map(int, version_str.split('.')))
