"""
DO NOT EDIT - Auto-generated file
Generated by talon-manifest-generator v2.0.0

This file provides:
- Package version checking via input_map_version() action
"""
import json
from pathlib import Path
from talon import Module

mod = Module()

try:
    # Version is cached at import. Restart or save this file to pick up changes.
    with open(Path(__file__).parent / 'manifest.json', 'r', encoding='utf-8') as f:
        _VERSION = tuple(map(int, json.load(f)['version'].split('.')))
except Exception as e:
    print(f"ERROR: talon-input-map failed to load version from manifest.json: {e}")
    _VERSION = (0, 0, 0)

@mod.action_class
class Actions:
    def input_map_version() -> tuple[int, int, int]:
        """
        Returns the package version as (major, minor, patch).

        Usage: actions.user.input_map_version() >= (1, 2, 0)
        """
        return _VERSION
